name             'ruby_app'
maintainer       'Artem Bykov'
maintainer_email 'artem.bikov@gmail.com'
license          'All rights reserved'
description      'Installs/Configures ruby_app'
long_description 'Installs/Configures ruby_app'
version          '0.1.0'
